name: Publish
on:
  push:
    branches:
      - "main"
    tags:        
      - 'v*.*.*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: holusion/e-corpus
  DEPLOY_HOST: ecorpus.holusion.com

concurrency: 
  group: publish-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker-publish:
    name: Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
